inherit_gem:
  caliber: config/all.yml

Layout/MultilineOperationIndentation:
  Enabled: false
Lint/ImplicitStringConcatenation:
  Exclude:
    - "scripts/ruby/strings/concatenation"
Performance:
  Enabled: false
Style/For:
  Exclude:
    - "scripts/ruby/loops"
Style/SelectByRegexp:
  Exclude:
    - "scripts/ruby/arrays/search"
Style/SingleArgumentDig:
  Exclude:
    - "scripts/ruby/hashes/lookup"
Style/StructInheritance:
  Exclude:
    - "scripts/ruby/structs/inheritance"
Style/RedundantFetchBlock:
  Exclude:
    - "scripts/ruby/hashes/lookup"
Style/OpenStructUse:
  Exclude:
    - "scripts/ruby/structs/construction"
    - "scripts/ruby/values/initialization"
    - "scripts/ruby/values/reading"
    - "scripts/ruby/values/writing"
