inherit_gem:
  caliber: config/all.yml

Layout/MultilineOperationIndentation:
  Enabled: false
Lint/ImplicitStringConcatenation:
  Exclude:
    - "scripts/strings/concatenation"
Lint/UselessAssignment:
  Exclude:
    - "scripts/arrays/concatenation"
Performance:
  Enabled: false
Style/For:
  Exclude:
    - "scripts/loops"
Style/SelectByRegexp:
  Exclude:
    - "scripts/arrays/search"
Style/SingleArgumentDig:
  Exclude:
    - "scripts/hashes/lookup"
Style/StructInheritance:
  Exclude:
    - "scripts/values/inheritance"
Style/RedundantFetchBlock:
  Exclude:
    - "scripts/hashes/lookup"
Style/OpenStructUse:
  Exclude:
    - "scripts/values/initialization"
    - "scripts/values/reading"
    - "scripts/values/writing"
