inherit_from:
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/ruby.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/rake.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/rspec.yml

Layout/MultilineOperationIndentation:
  Enabled: false
Lint/ImplicitStringConcatenation:
  Exclude:
    - "scripts/ruby/strings/concatenation.rb"
Style/SingleArgumentDig:
  Exclude:
    - "scripts/ruby/hashes/lookup.rb"
Style/StructInheritance:
  Exclude:
    - "scripts/ruby/structs/inheritance.rb"
Style/RedundantFetchBlock:
  Exclude:
    - "scripts/ruby/hashes/lookup.rb"
