inherit_from:
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/master/configurations/rubocop/ruby.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/master/configurations/rubocop/rspec.yml

Performance/OpenStruct:
  Exclude:
    - "scripts/ruby/structs/construction.rb"
    - "scripts/ruby/values/construction.rb"

Performance/StringReplacement:
  Exclude:
    - "scripts/ruby/strings/substrings.rb"

Style/StructInheritance:
  Exclude:
    - "scripts/ruby/structs/inheritance.rb"
