inherit_gem:
  caliber:
    - config/ruby.yml
    - config/rake.yml
    - config/rspec.yml

Layout/MultilineOperationIndentation:
  Enabled: false
Lint/ImplicitStringConcatenation:
  Exclude:
    - "scripts/ruby/strings/concatenation.rb"
Style/For:
  Exclude:
    - "scripts/ruby/loops.rb"
Style/SelectByRegexp:
  Exclude:
    - "scripts/ruby/arrays/search.rb"
Style/SingleArgumentDig:
  Exclude:
    - "scripts/ruby/hashes/lookup.rb"
Style/StructInheritance:
  Exclude:
    - "scripts/ruby/structs/inheritance.rb"
Style/RedundantFetchBlock:
  Exclude:
    - "scripts/ruby/hashes/lookup.rb"
Style/OpenStructUse:
  Exclude:
    - "scripts/ruby/structs/construction.rb"
    - "scripts/ruby/values/construction.rb"
    - "scripts/ruby/values/reading.rb"
    - "scripts/ruby/values/writing.rb"
