:toc: macro
:toclevels: 5
:figure-caption!:

= Benchmarks

[link=https://circleci.com/gh/bkuhlmann/benchmarks]
image::https://circleci.com/gh/bkuhlmann/benchmarks.svg?style=svg[Circle CI Status]

Benchmarks is a collection of Ruby micro benchmarks which can be cloned and run locally or used as
an information point of reference. The various statistics on Ruby performance captured within this
project may or may not surprise you.

toc::[]

== Features

* Uses link:https://github.com/evanphx/benchmark-ips[Benchmark IPS] to calculate CPU/speed results.

== Screencasts

[link=https://www.alchemists.io/screencasts/benchmarks]
image::https://www.alchemists.io/images/screencasts/benchmarks/cover.svg[Screencast,600,240,role=focal_point]

== Requirements

. link:https://www.ruby-lang.org[Ruby]

== Setup

To install, run:

[source,bash]
----
git clone https://github.com/bkuhlmann/benchmarks.git
cd benchmarks
git checkout 0.17.1
bin/setup
----

== Usage

Every benchmark is executable. To run, copy a benchmark file path and pass it to Ruby. Example:

[source,bash]
----
ruby scripts/ruby/strings/split.rb
----

You can also avoid running any of the benchmarks locally by browsing any of the scripts located in
the `scripts` folder and looking for the benchmark results at the end of the file.

== Development

To contribute, run:

[source,bash]
----
git clone https://github.com/bkuhlmann/benchmarks.git
cd benchmarks
bin/setup
----

== Tests

To test, run:

[source,bash]
----
bundle exec rake
----

== Versioning

Read link:https://semver.org[Semantic Versioning] for details. Briefly, it means:

* Major (X.y.z) - Incremented for any backwards incompatible public API changes.
* Minor (x.Y.z) - Incremented for new, backwards compatible, public API enhancements/fixes.
* Patch (x.y.Z) - Incremented for small, backwards compatible, bug fixes.

== Code of Conduct

Please note that this project is released with a link:CODE_OF_CONDUCT.adoc[CODE OF CONDUCT]. By
participating in this project you agree to abide by its terms.

== Contributions

Read link:CONTRIBUTING.adoc[CONTRIBUTING] for details.

== License

Read link:LICENSE.adoc[LICENSE] for details.

== History

Read link:CHANGES.adoc[CHANGES] for details.

== Credits

Engineered by link:https://www.alchemists.io/team/brooke_kuhlmann[Brooke Kuhlmann].
